---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-webui
  labels:
    app.kubernetes.io/version: "v3.1.1"
    project: free5gc
    nf: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      project: free5gc
      nf: webui
  template:
    metadata:
      labels:
        project: free5gc
        nf: webui
    spec:
      initContainers:
      - name: wait-mongo
        image: busybox:1.32.0
        env:
        - name: DEPENDENCIES
          value: mongodb:27017
        command: ["sh", "-c", "until nc -z $DEPENDENCIES; do echo waiting for the MongoDB; sleep 2; done;"]
      containers:
      - name: webui
        image: towards5gs/free5gc-webui:v3.1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        command: ["./webconsole"]
        args: ["-c", "../config/webuicfg.yaml"]
        env:
          - name: GIN_MODE
            value: release
        volumeMounts:
        - mountPath: /free5gc/config/
          name: webui-volume
        resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
        readinessProbe:
          initialDelaySeconds: 0
          periodSeconds: 1
          timeoutSeconds: 1
          failureThreshold:  40
          successThreshold: 1
          httpGet:
            scheme: HTTP
            port: 5000
        livenessProbe:
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          httpGet:
            scheme: HTTP
            port: 5000
      dnsPolicy: ClusterFirst
      restartPolicy: Always

      volumes:
      - name: webui-volume
        projected:
          sources:
          - configMap:
              name: webui-configmap
